'use client';

import React, { createContext, useContext, useState, useCallback } from 'react';

export type SupportedLanguage = 'en' | 'ceb' | 'zh' | 'ko' | 'ja' | 'es' | 'fr' | 'de' | 'vi' | 'tr';

export interface Translations {
  // Nav
  trade: string;
  portfolio: string;
  vaults: string;
  history: string;
  rewards: string;
  leaderboard: string;
  apiSdk: string;
  docs: string;
  ecosystem: string;
  developerSuite: string;
  systemWhitepaper: string;
  onChainExplorer: string;
  securityInfra: string;
  sessionKeys: string;
  contractSource: string;
  growthRankings: string;

  // Market Header
  markPrice: string;
  oraclePrice: string;
  change24h: string;
  volume24h: string;
  openInterest: string;
  fundingRate: string;

  // Order Form
  placeOrder: string;
  buyLong: string;
  sellShort: string;
  market: string;
  limit: string;
  stopMarket: string;
  stopLimit: string;
  margin: string;
  leverage: string;
  priceImpact: string;
  maxSlippage: string;
  deposit: string;
  withdraw: string;
  availableToTrade: string;
  currentPosition: string;
  stopTriggerPrice: string;
  limitPrice: string;

  // Positions Table
  positions: string;
  openOrders: string;
  tradeHistory: string;
  entryPrice: string;
  liqPrice: string;
  pnl: string;
  action: string;
  closePosition: string;
  editTpSl: string;
  sharePnl: string;
  cancelOrder: string;

  // Orderbook
  orderBook: string;
  trades: string;
  priceUsdc: string;
  size: string;
  total: string;
  spread: string;

  // Portfolio / Vaults
  liquidityVault: string;
  totalValueLocked: string;
  estimatedApr: string;
  totalSharesMinted: string;
  yourPoolShare: string;
  yourStakedBalance: string;
  depositUsdc: string;
  withdrawUsdc: string;
  stakingYield: string;
  elpPrice: string;
  dailyYield: string;
  redeemShares: string;

  // Rewards
  referralProgram: string;
  unclaimedKickback: string;
  lifetimeEarnings: string;
  referredTraders: string;
  tradingVolume30d: string;
  vipTier: string;
  feeDiscount: string;
  copyReferralLink: string;
  claimRewards: string;

  // Leaderboard
  rank: string;
  trader: string;
  realizedPnl: string;
  winRate: string;
  totalTrades: string;
  yourRank: string;

  // History
  tradeLog: string;
  exitPrice: string;
  feePaid: string;
  txHash: string;
  filterByMarket: string;
  allMarkets: string;

  // General
  connectWallet: string;
  noDataYet: string;
  loading: string;
  settings: string;
  language: string;
}

const TRANSLATIONS: Record<SupportedLanguage, Translations> = {
  en: {
    trade: 'Trade',
    portfolio: 'Portfolio',
    vaults: 'Vaults',
    history: 'History',
    rewards: 'Rewards',
    leaderboard: 'Leaderboard',
    apiSdk: 'API & Client SDK',
    docs: 'System Whitepaper',
    ecosystem: 'Ecosystem',
    developerSuite: 'Developer Suite',
    systemWhitepaper: 'System Whitepaper',
    onChainExplorer: 'On-Chain Explorer',
    securityInfra: 'Security & Infra',
    sessionKeys: '1-Click Session Keys',
    contractSource: 'Contract Source',
    growthRankings: 'Growth & Rankings',
    markPrice: 'Mark Price',
    oraclePrice: 'Oracle Price',
    change24h: '24h Change',
    volume24h: '24h Volume',
    openInterest: 'Open Interest',
    fundingRate: 'Funding / 1h',
    placeOrder: 'Place Order',
    buyLong: 'Buy / Long',
    sellShort: 'Sell / Short',
    market: 'Market',
    limit: 'Limit',
    stopMarket: 'Stop Market',
    stopLimit: 'Stop Limit',
    margin: 'Margin',
    leverage: 'Leverage',
    priceImpact: 'Price Impact',
    maxSlippage: 'Max Slippage',
    deposit: 'Deposit',
    withdraw: 'Withdraw',
    availableToTrade: 'Available to Trade',
    currentPosition: 'Current Position',
    stopTriggerPrice: 'Stop Trigger Price',
    limitPrice: 'Limit Price',
    positions: 'Positions',
    openOrders: 'Open Orders',
    tradeHistory: 'Trade History',
    entryPrice: 'Entry Price',
    liqPrice: 'Liq. Price',
    pnl: 'PnL',
    action: 'Action',
    closePosition: 'Close Position',
    editTpSl: 'Edit TP/SL',
    sharePnl: 'Share PnL',
    cancelOrder: 'Cancel Order',
    orderBook: 'Order Book',
    trades: 'Trades',
    priceUsdc: 'Price (USDC)',
    size: 'Size',
    total: 'Total',
    spread: 'Spread',
    liquidityVault: 'Liquidity Provider Vault',
    totalValueLocked: 'Total Value Locked (TVL)',
    estimatedApr: 'Estimated APR',
    totalSharesMinted: 'Total Shares Minted',
    yourPoolShare: 'Your Pool Share',
    yourStakedBalance: 'Your Staked Balance',
    depositUsdc: 'Deposit USDC',
    withdrawUsdc: 'Withdraw USDC',
    stakingYield: 'Staking Yield',
    elpPrice: 'ELP Price',
    dailyYield: 'Daily Yield',
    redeemShares: 'Redeem Shares',
    referralProgram: 'Referral Program',
    unclaimedKickback: 'Unclaimed Kickback',
    lifetimeEarnings: 'Lifetime Earnings',
    referredTraders: 'Referred Traders',
    tradingVolume30d: '30d Trading Volume',
    vipTier: 'VIP Tier',
    feeDiscount: 'Fee Discount',
    copyReferralLink: 'Copy Referral Link',
    claimRewards: 'Claim Rewards',
    rank: 'Rank',
    trader: 'Trader',
    realizedPnl: 'Realized PnL',
    winRate: 'Win Rate',
    totalTrades: 'Total Trades',
    yourRank: 'Your Rank',
    tradeLog: 'Trade Log',
    exitPrice: 'Exit Price',
    feePaid: 'Fee Paid',
    txHash: 'Tx Hash',
    filterByMarket: 'Filter by Market',
    allMarkets: 'All Markets',
    connectWallet: 'Connect Wallet',
    noDataYet: 'No data yet',
    loading: 'Loading...',
    settings: 'Settings',
    language: 'Language',
  },
  ceb: {
    trade: 'Pagbaligya',
    portfolio: 'Portpolyo',
    vaults: 'Mga Vault',
    history: 'Kaagi',
    rewards: 'Mga Ganti',
    leaderboard: 'Klasipikasyon',
    apiSdk: 'API ug Client SDK',
    docs: 'Dokumentasyon',
    ecosystem: 'Ekosistema',
    developerSuite: 'Mga Himan sa Developer',
    systemWhitepaper: 'Puti nga Papel sa Sistema',
    onChainExplorer: 'Eksplorador sa Chain',
    securityInfra: 'Seguridad ug Infra',
    sessionKeys: '1-Click Session Keys',
    contractSource: 'Kodigo sa Kontrata',
    growthRankings: 'Pagtubo ug Posisyon',
    markPrice: 'Mark nga Presyo',
    oraclePrice: 'Presyo sa Oracle',
    change24h: 'Bag-o sa 24h',
    volume24h: 'Balyum sa 24h',
    openInterest: 'Nabilin nga Entres',
    fundingRate: 'Kabayranan / 1h',
    placeOrder: 'Paghimo og Order',
    buyLong: 'Palit / Long',
    sellShort: 'Baligya / Short',
    market: 'Merkado',
    limit: 'Limitado',
    stopMarket: 'Stop Merkado',
    stopLimit: 'Stop Limitado',
    margin: 'Puhunan',
    leverage: 'Leverage',
    priceImpact: 'Epekto sa Presyo',
    maxSlippage: 'Max Slippage',
    deposit: 'Deposito',
    withdraw: 'Kuhag Kuwarta',
    availableToTrade: 'Magamit sa Negosyo',
    currentPosition: 'Karon nga Posisyon',
    stopTriggerPrice: 'Presyo sa Trigger',
    limitPrice: 'Presyo sa Limit',
    positions: 'Mga Posisyon',
    openOrders: 'Nabilin nga Orders',
    tradeHistory: 'Kaagi sa Negosyo',
    entryPrice: 'Presyo sa Pagsulod',
    liqPrice: 'Presyo sa Likidasyon',
    pnl: 'KITA (PnL)',
    action: 'Lihok',
    closePosition: 'Sirad-i ang Posisyon',
    editTpSl: 'Usba ang TP/SL',
    sharePnl: 'I-pakigbahin ang PnL',
    cancelOrder: 'Kanselaha ang Order',
    orderBook: 'Libro sa Orders',
    trades: 'Mga Negosyo',
    priceUsdc: 'Presyo (USDC)',
    size: 'Kadak-on',
    total: 'Tanan',
    spread: 'Spred',
    liquidityVault: 'Vault sa Likido',
    totalValueLocked: 'Total nga Bili nga Gi-lock (TVL)',
    estimatedApr: 'Gibanabana nga APR',
    totalSharesMinted: 'Total nga Shares nga Na-mint',
    yourPoolShare: 'Imong Pool Share',
    yourStakedBalance: 'Imong Gi-stake nga Balanse',
    depositUsdc: 'I-deposito ang USDC',
    withdrawUsdc: 'I-withdraw ang USDC',
    stakingYield: 'Yield sa Staking',
    elpPrice: 'Presyo sa ELP',
    dailyYield: 'Yield sa Adlaw',
    redeemShares: 'I-redeem ang Shares',
    referralProgram: 'Programa sa Referral',
    unclaimedKickback: 'Wala pa Na-claim nga Kickback',
    lifetimeEarnings: 'Kita sa Tibuok Kinabuhi',
    referredTraders: 'Mga Gi-refer nga Traders',
    tradingVolume30d: 'Bolumen sa 30 ka Adlaw',
    vipTier: 'VIP Tier',
    feeDiscount: 'Diskuwento sa Bayad',
    copyReferralLink: 'Kopyaha ang Referral Link',
    claimRewards: 'I-claim ang Ganti',
    rank: 'Ranggo',
    trader: 'Negosyante',
    realizedPnl: 'Tinuod nga PnL',
    winRate: 'Porsiyento sa Kadaugan',
    totalTrades: 'Total nga Negosyo',
    yourRank: 'Imong Ranggo',
    tradeLog: 'Log sa Negosyo',
    exitPrice: 'Presyo sa Paggawas',
    feePaid: 'Bayad nga Na-bayaran',
    txHash: 'Tx Hash',
    filterByMarket: 'I-filter sa Merkado',
    allMarkets: 'Tanang Merkado',
    connectWallet: 'I-connect ang Wallet',
    noDataYet: 'Walay datos pa',
    loading: 'Nagkarga...',
    settings: 'Mga Setting',
    language: 'Pinulongan',
  },
  zh: {
    trade: '交易',
    portfolio: '投资组合',
    vaults: '金库',
    history: '历史记录',
    rewards: '奖励计划',
    leaderboard: '排行榜',
    apiSdk: 'API & 客户端 SDK',
    docs: '系统白皮书',
    ecosystem: '生态系统',
    developerSuite: '开发者工具包',
    systemWhitepaper: '架构白皮书',
    onChainExplorer: '链上浏览器',
    securityInfra: '安全与基础设施',
    sessionKeys: '一键交易密钥',
    contractSource: '智能合约源码',
    growthRankings: '增长与排名',
    markPrice: '标记价格',
    oraclePrice: '预言机价格',
    change24h: '24小时涨跌',
    volume24h: '24小时成交量',
    openInterest: '未平仓合约',
    fundingRate: '资金费率 / 1h',
    placeOrder: '下单',
    buyLong: '买入 / 做多',
    sellShort: '卖出 / 做空',
    market: '市价',
    limit: '限价',
    stopMarket: '止损市价',
    stopLimit: '止损限价',
    margin: '保证金',
    leverage: '杠杆倍数',
    priceImpact: '价格影响',
    maxSlippage: '最大滑点',
    deposit: '充值',
    withdraw: '提现',
    availableToTrade: '可用保证金',
    currentPosition: '当前持仓',
    stopTriggerPrice: '触发价格',
    limitPrice: '委托价格',
    positions: '持仓列表',
    openOrders: '当前委托',
    tradeHistory: '成交历史',
    entryPrice: '开仓均价',
    liqPrice: '强平价格',
    pnl: '未实现盈亏',
    action: '操作',
    closePosition: '平仓',
    editTpSl: '止盈/止损',
    sharePnl: '分享盈亏',
    cancelOrder: '撤单',
    orderBook: '订单簿',
    trades: '最新成交',
    priceUsdc: '价格 (USDC)',
    size: '数量',
    total: '累计',
    spread: '价差',
    liquidityVault: '流动性提供者金库',
    totalValueLocked: '总锁仓量 (TVL)',
    estimatedApr: '预估年化收益率',
    totalSharesMinted: '已铸造总份额',
    yourPoolShare: '你的池份额',
    yourStakedBalance: '你的质押余额',
    depositUsdc: '存入 USDC',
    withdrawUsdc: '提取 USDC',
    stakingYield: '质押收益',
    elpPrice: 'ELP 价格',
    dailyYield: '日收益',
    redeemShares: '赎回份额',
    referralProgram: '推荐计划',
    unclaimedKickback: '未领取返佣',
    lifetimeEarnings: '累计收益',
    referredTraders: '推荐交易者',
    tradingVolume30d: '30日交易量',
    vipTier: 'VIP 等级',
    feeDiscount: '手续费折扣',
    copyReferralLink: '复制推荐链接',
    claimRewards: '领取奖励',
    rank: '排名',
    trader: '交易者',
    realizedPnl: '已实现盈亏',
    winRate: '胜率',
    totalTrades: '总交易数',
    yourRank: '你的排名',
    tradeLog: '交易记录',
    exitPrice: '退出价格',
    feePaid: '已付手续费',
    txHash: '交易哈希',
    filterByMarket: '按市场筛选',
    allMarkets: '全部市场',
    connectWallet: '连接钱包',
    noDataYet: '暂无数据',
    loading: '加载中...',
    settings: '设置',
    language: '语言',
  },
  ko: {
    trade: '거래',
    portfolio: '포트폴리오',
    vaults: '볼트',
    history: '내역',
    rewards: '리워드',
    leaderboard: '리더보드',
    apiSdk: 'API & 클라이언트 SDK',
    docs: '시스템 백서',
    ecosystem: '생태계',
    developerSuite: '개발자 도구',
    systemWhitepaper: '아키텍처 백서',
    onChainExplorer: '온체인 탐색기',
    securityInfra: '보안 및 인프라',
    sessionKeys: '원클릭 세션 키',
    contractSource: '컨트랙트 소스 코드',
    growthRankings: '성장 및 랭킹',
    markPrice: '마크 가격',
    oraclePrice: '오라클 가격',
    change24h: '24시간 변동',
    volume24h: '24시간 거래량',
    openInterest: '미결제 약정',
    fundingRate: '펀딩 비율 / 1시간',
    placeOrder: '주문 하기',
    buyLong: '매수 / 롱',
    sellShort: '매도 / 숏',
    market: '시장가',
    limit: '지정가',
    stopMarket: '스탑 시장가',
    stopLimit: '스탑 지정가',
    margin: '증거금',
    leverage: '레버리지',
    priceImpact: '가격 영향',
    maxSlippage: '최대 슬리피지',
    deposit: '입금',
    withdraw: '출금',
    availableToTrade: '거래 가능 금액',
    currentPosition: '현재 포지션',
    stopTriggerPrice: '스탑 발동 가격',
    limitPrice: '지정 가격',
    positions: '포지션',
    openOrders: '미체결 주문',
    tradeHistory: '거래 내역',
    entryPrice: '진입가',
    liqPrice: '청산가',
    pnl: '손익(PnL)',
    action: '작업',
    closePosition: '포지션 종료',
    editTpSl: 'TP/SL 수정',
    sharePnl: '손익 공유',
    cancelOrder: '주문 취소',
    orderBook: '오더북',
    trades: '체결 내역',
    priceUsdc: '가격 (USDC)',
    size: '수량',
    total: '합계',
    spread: '스프레드',
    liquidityVault: '유동성 공급자 볼트',
    totalValueLocked: '총 예치금 (TVL)',
    estimatedApr: '예상 연이율',
    totalSharesMinted: '발행된 총 지분',
    yourPoolShare: '나의 풀 지분',
    yourStakedBalance: '나의 스테이킹 잔액',
    depositUsdc: 'USDC 입금',
    withdrawUsdc: 'USDC 출금',
    stakingYield: '스테이킹 수익',
    elpPrice: 'ELP 가격',
    dailyYield: '일일 수익',
    redeemShares: '지분 상환',
    referralProgram: '추천 프로그램',
    unclaimedKickback: '미수령 킥백',
    lifetimeEarnings: '누적 수익',
    referredTraders: '추천 트레이더',
    tradingVolume30d: '30일 거래량',
    vipTier: 'VIP 등급',
    feeDiscount: '수수료 할인',
    copyReferralLink: '추천 링크 복사',
    claimRewards: '보상 수령',
    rank: '순위',
    trader: '트레이더',
    realizedPnl: '실현 손익',
    winRate: '승률',
    totalTrades: '총 거래수',
    yourRank: '나의 순위',
    tradeLog: '거래 기록',
    exitPrice: '청산 가격',
    feePaid: '지불 수수료',
    txHash: '트랜잭션 해시',
    filterByMarket: '시장별 필터',
    allMarkets: '전체 시장',
    connectWallet: '지갑 연결',
    noDataYet: '데이터 없음',
    loading: '로딩 중...',
    settings: '설정',
    language: '언어',
  },
  ja: {
    trade: '取引',
    portfolio: 'ポートフォリオ',
    vaults: 'ボルト',
    history: '履歴',
    rewards: '報酬',
    leaderboard: 'リーダーボード',
    apiSdk: 'API & クライアント SDK',
    docs: '白書',
    ecosystem: 'エコシステム',
    developerSuite: '開発者ツール',
    systemWhitepaper: 'システム白書',
    onChainExplorer: 'オンチェーンエクスプローラー',
    securityInfra: 'セキュリティ',
    sessionKeys: 'ワンクリックセッションキー',
    contractSource: 'コントラクトコード',
    growthRankings: 'ランキング',
    markPrice: 'マーク価格',
    oraclePrice: 'オラクル価格',
    change24h: '24時間前比',
    volume24h: '24時間出来高',
    openInterest: '未決済建玉',
    fundingRate: '資金調達率 / 1h',
    placeOrder: '注文を作成',
    buyLong: '買い / ロング',
    sellShort: '売り / ショート',
    market: '成行',
    limit: '指値',
    stopMarket: 'ストップ成行',
    stopLimit: 'ストップ指値',
    margin: '証拠金',
    leverage: 'レバレッジ',
    priceImpact: '価格影響',
    maxSlippage: '許容スリッページ',
    deposit: '入金',
    withdraw: '出金',
    availableToTrade: '利用可能証拠金',
    currentPosition: '現在のポジション',
    stopTriggerPrice: 'トリガー価格',
    limitPrice: '指値価格',
    positions: '保有ポジション',
    openOrders: '未決済注文',
    tradeHistory: '取引履歴',
    entryPrice: '参入価格',
    liqPrice: '清算価格',
    pnl: '損益',
    action: '操作',
    closePosition: '決済',
    editTpSl: 'TP/SL 編集',
    sharePnl: '損益を共有',
    cancelOrder: '注文キャンセル',
    orderBook: '板情報',
    trades: '歩み値',
    priceUsdc: '価格 (USDC)',
    size: '数量',
    total: '合計',
    spread: 'スプレッド',
    liquidityVault: '流動性プロバイダーボールト',
    totalValueLocked: '総ロック額 (TVL)',
    estimatedApr: '推定年利率',
    totalSharesMinted: '発行済み総シェア',
    yourPoolShare: 'あなたのプールシェア',
    yourStakedBalance: 'ステーキング残高',
    depositUsdc: 'USDC を入金',
    withdrawUsdc: 'USDC を出金',
    stakingYield: 'ステーキング利回り',
    elpPrice: 'ELP 価格',
    dailyYield: '日次利回り',
    redeemShares: 'シェアを償還',
    referralProgram: 'リファラルプログラム',
    unclaimedKickback: '未請求キックバック',
    lifetimeEarnings: '累計収益',
    referredTraders: '紹介トレーダー',
    tradingVolume30d: '30日間取引量',
    vipTier: 'VIP ティア',
    feeDiscount: '手数料割引',
    copyReferralLink: '紹介リンクをコピー',
    claimRewards: '報酬を請求',
    rank: '順位',
    trader: 'トレーダー',
    realizedPnl: '実現損益',
    winRate: '勝率',
    totalTrades: '総取引数',
    yourRank: 'あなたの順位',
    tradeLog: '取引ログ',
    exitPrice: '決済価格',
    feePaid: '支払手数料',
    txHash: 'Txハッシュ',
    filterByMarket: '市場でフィルター',
    allMarkets: '全市場',
    connectWallet: 'ウォレット接続',
    noDataYet: 'データなし',
    loading: '読み込み中...',
    settings: '設定',
    language: '言語',
  },
  es: {
    trade: 'Operar',
    portfolio: 'Portafolio',
    vaults: 'Bóvedas',
    history: 'Historial',
    rewards: 'Recompensas',
    leaderboard: 'Clasificación',
    apiSdk: 'API & SDK',
    docs: 'Libro Blanco',
    ecosystem: 'Ecosistema',
    developerSuite: 'Herramientas de Desarrollador',
    systemWhitepaper: 'Libro Blanco',
    onChainExplorer: 'Explorador On-Chain',
    securityInfra: 'Seguridad',
    sessionKeys: 'Claves de Sesión 1-Clic',
    contractSource: 'Código de Contrato',
    growthRankings: 'Crecimiento y Rangos',
    markPrice: 'Precio Mark',
    oraclePrice: 'Precio Oráculo',
    change24h: 'Cambio 24h',
    volume24h: 'Volumen 24h',
    openInterest: 'Interés Abierto',
    fundingRate: 'Financiación / 1h',
    placeOrder: 'Realizar Orden',
    buyLong: 'Comprar / Long',
    sellShort: 'Vender / Short',
    market: 'Mercado',
    limit: 'Límite',
    stopMarket: 'Stop Mercado',
    stopLimit: 'Stop Límite',
    margin: 'Margen',
    leverage: 'Apalancamiento',
    priceImpact: 'Impacto de Precio',
    maxSlippage: 'Slippage Máximo',
    deposit: 'Depositar',
    withdraw: 'Retirar',
    availableToTrade: 'Disponible para Operar',
    currentPosition: 'Posición Actual',
    stopTriggerPrice: 'Precio de Activación',
    limitPrice: 'Precio Límite',
    positions: 'Posiciones',
    openOrders: 'Órdenes Abiertas',
    tradeHistory: 'Historial de Operaciones',
    entryPrice: 'Precio Entrado',
    liqPrice: 'Precio Liq.',
    pnl: 'PnL',
    action: 'Acción',
    closePosition: 'Cerrar Posición',
    editTpSl: 'Editar TP/SL',
    sharePnl: 'Compartir PnL',
    cancelOrder: 'Cancelar Orden',
    orderBook: 'Libro de Órdenes',
    trades: 'Operaciones',
    priceUsdc: 'Precio (USDC)',
    size: 'Tamaño',
    total: 'Total',
    spread: 'Spread',
    liquidityVault: 'Bóveda de Liquidez',
    totalValueLocked: 'Valor Total Bloqueado (TVL)',
    estimatedApr: 'APR Estimado',
    totalSharesMinted: 'Acciones Totales Emitidas',
    yourPoolShare: 'Tu Participación en el Pool',
    yourStakedBalance: 'Tu Saldo en Stake',
    depositUsdc: 'Depositar USDC',
    withdrawUsdc: 'Retirar USDC',
    stakingYield: 'Rendimiento de Staking',
    elpPrice: 'Precio ELP',
    dailyYield: 'Rendimiento Diario',
    redeemShares: 'Canjear Acciones',
    referralProgram: 'Programa de Referidos',
    unclaimedKickback: 'Comisión No Reclamada',
    lifetimeEarnings: 'Ganancias Totales',
    referredTraders: 'Traders Referidos',
    tradingVolume30d: 'Volumen 30 Días',
    vipTier: 'Nivel VIP',
    feeDiscount: 'Descuento en Comisiones',
    copyReferralLink: 'Copiar Enlace de Referido',
    claimRewards: 'Reclamar Recompensas',
    rank: 'Rango',
    trader: 'Trader',
    realizedPnl: 'PnL Realizado',
    winRate: 'Tasa de Victorias',
    totalTrades: 'Total de Operaciones',
    yourRank: 'Tu Rango',
    tradeLog: 'Registro de Operaciones',
    exitPrice: 'Precio de Salida',
    feePaid: 'Comisión Pagada',
    txHash: 'Hash de Tx',
    filterByMarket: 'Filtrar por Mercado',
    allMarkets: 'Todos los Mercados',
    connectWallet: 'Conectar Billetera',
    noDataYet: 'Sin datos aún',
    loading: 'Cargando...',
    settings: 'Configuración',
    language: 'Idioma',
  },
  fr: {
    trade: 'Trader',
    portfolio: 'Portefeuille',
    vaults: 'Coffres',
    history: 'Historique',
    rewards: 'Récompenses',
    leaderboard: 'Classement',
    apiSdk: 'API & SDK Client',
    docs: 'Livre Blanc',
    ecosystem: 'Écosystème',
    developerSuite: 'Outils Développeur',
    systemWhitepaper: 'Livre Blanc Système',
    onChainExplorer: 'Explorateur On-Chain',
    securityInfra: 'Sécurité & Infra',
    sessionKeys: 'Clés de Session 1-Clic',
    contractSource: 'Code du Contrat',
    growthRankings: 'Croissance et Rang',
    markPrice: 'Prix Mark',
    oraclePrice: 'Prix Oracle',
    change24h: 'Variation 24h',
    volume24h: 'Volume 24h',
    openInterest: 'Intérêt Ouvert',
    fundingRate: 'Financement / 1h',
    placeOrder: 'Passer Commande',
    buyLong: 'Achat / Long',
    sellShort: 'Vente / Short',
    market: 'Marché',
    limit: 'Limite',
    stopMarket: 'Stop Marché',
    stopLimit: 'Stop Limite',
    margin: 'Marge',
    leverage: 'Levier',
    priceImpact: 'Impact Prix',
    maxSlippage: 'Glissement Max',
    deposit: 'Déposer',
    withdraw: 'Retirer',
    availableToTrade: 'Disponible pour Trader',
    currentPosition: 'Position Actuelle',
    stopTriggerPrice: 'Prix de Déclenchement',
    limitPrice: 'Prix Limite',
    positions: 'Positions',
    openOrders: 'Ordres Ouverts',
    tradeHistory: 'Historique de Trade',
    entryPrice: 'Prix d\'Entrée',
    liqPrice: 'Prix Liq.',
    pnl: 'PnL',
    action: 'Action',
    closePosition: 'Fermer Position',
    editTpSl: 'Éditer TP/SL',
    sharePnl: 'Partager PnL',
    cancelOrder: 'Annuler Ordre',
    orderBook: 'Carnet d\'Ordres',
    trades: 'Transacts',
    priceUsdc: 'Prix (USDC)',
    size: 'Taille',
    total: 'Total',
    spread: 'Écart',
    liquidityVault: 'Coffre de Liquidité',
    totalValueLocked: 'Valeur Totale Verrouillée (TVL)',
    estimatedApr: 'APR Estimé',
    totalSharesMinted: 'Parts Totales Émises',
    yourPoolShare: 'Votre Part du Pool',
    yourStakedBalance: 'Votre Solde Staké',
    depositUsdc: 'Déposer USDC',
    withdrawUsdc: 'Retirer USDC',
    stakingYield: 'Rendement de Staking',
    elpPrice: 'Prix ELP',
    dailyYield: 'Rendement Quotidien',
    redeemShares: 'Racheter les Parts',
    referralProgram: 'Programme de Parrainage',
    unclaimedKickback: 'Commission Non Réclamée',
    lifetimeEarnings: 'Gains Cumulés',
    referredTraders: 'Traders Parrainés',
    tradingVolume30d: 'Volume 30 Jours',
    vipTier: 'Niveau VIP',
    feeDiscount: 'Réduction de Frais',
    copyReferralLink: 'Copier le Lien de Parrainage',
    claimRewards: 'Réclamer les Récompenses',
    rank: 'Rang',
    trader: 'Trader',
    realizedPnl: 'PnL Réalisé',
    winRate: 'Taux de Victoire',
    totalTrades: 'Total des Transactions',
    yourRank: 'Votre Rang',
    tradeLog: 'Journal des Transactions',
    exitPrice: 'Prix de Sortie',
    feePaid: 'Frais Payés',
    txHash: 'Hash de Tx',
    filterByMarket: 'Filtrer par Marché',
    allMarkets: 'Tous les Marchés',
    connectWallet: 'Connecter le Portefeuille',
    noDataYet: 'Aucune donnée disponible',
    loading: 'Chargement...',
    settings: 'Paramètres',
    language: 'Langue',
  },
  de: {
    trade: 'Handeln',
    portfolio: 'Portfolio',
    vaults: 'Tresore',
    history: 'Verlauf',
    rewards: 'Belohnungen',
    leaderboard: 'Bestenliste',
    apiSdk: 'API & Client SDK',
    docs: 'System-Whitepaper',
    ecosystem: 'Ökosystem',
    developerSuite: 'Entwickler-Tools',
    systemWhitepaper: 'System-Whitepaper',
    onChainExplorer: 'On-Chain-Explorer',
    securityInfra: 'Sicherheit & Infra',
    sessionKeys: '1-Klick-Sitzungsschlüssel',
    contractSource: 'Vertragsquellcode',
    growthRankings: 'Wachstum & Rang',
    markPrice: 'Mark-Preis',
    oraclePrice: 'Orakel-Preis',
    change24h: '24h Änderung',
    volume24h: '24h Volumen',
    openInterest: 'Offenes Interesse',
    fundingRate: 'Finanzierung / 1h',
    placeOrder: 'Order Platzieren',
    buyLong: 'Kaufen / Long',
    sellShort: 'Verkaufen / Short',
    market: 'Markt',
    limit: 'Limit',
    stopMarket: 'Stopp-Markt',
    stopLimit: 'Stopp-Limit',
    margin: 'Marge',
    leverage: 'Hebel',
    priceImpact: 'Preisauswirkung',
    maxSlippage: 'Max. Slippage',
    deposit: 'Einzahlen',
    withdraw: 'Auszahlen',
    availableToTrade: 'Verfügbares Kapital',
    currentPosition: 'Aktuelle Position',
    stopTriggerPrice: 'Stopp-Auslösepreis',
    limitPrice: 'Limit-Preis',
    positions: 'Positionen',
    openOrders: 'Offene Orders',
    tradeHistory: 'Handelsverlauf',
    entryPrice: 'Einstiegspreis',
    liqPrice: 'Liq.-Preis',
    pnl: 'PnL',
    action: 'Aktion',
    closePosition: 'Position Schließen',
    editTpSl: 'TP/SL Bearbeiten',
    sharePnl: 'PnL Teilen',
    cancelOrder: 'Order Stornieren',
    orderBook: 'Orderbuch',
    trades: 'Handel',
    priceUsdc: 'Preis (USDC)',
    size: 'Größe',
    total: 'Gesamt',
    spread: 'Spreizung',
    liquidityVault: 'Liquiditäts-Tresor',
    totalValueLocked: 'Gesamt gesperrter Wert (TVL)',
    estimatedApr: 'Geschätzter APR',
    totalSharesMinted: 'Gesamt geprägte Anteile',
    yourPoolShare: 'Ihr Pool-Anteil',
    yourStakedBalance: 'Ihr Staking-Guthaben',
    depositUsdc: 'USDC einzahlen',
    withdrawUsdc: 'USDC abheben',
    stakingYield: 'Staking-Rendite',
    elpPrice: 'ELP-Preis',
    dailyYield: 'Tägliche Rendite',
    redeemShares: 'Anteile einlösen',
    referralProgram: 'Empfehlungsprogramm',
    unclaimedKickback: 'Nicht beanspruchte Rückvergütung',
    lifetimeEarnings: 'Gesamteinnahmen',
    referredTraders: 'Empfohlene Trader',
    tradingVolume30d: '30-Tage-Handelsvolumen',
    vipTier: 'VIP-Stufe',
    feeDiscount: 'Gebührenrabatt',
    copyReferralLink: 'Empfehlungslink kopieren',
    claimRewards: 'Belohnungen einfordern',
    rank: 'Rang',
    trader: 'Trader',
    realizedPnl: 'Realisierter PnL',
    winRate: 'Gewinnrate',
    totalTrades: 'Gesamthandel',
    yourRank: 'Ihr Rang',
    tradeLog: 'Handelsprotokoll',
    exitPrice: 'Ausstiegspreis',
    feePaid: 'Bezahlte Gebühr',
    txHash: 'Tx-Hash',
    filterByMarket: 'Nach Markt filtern',
    allMarkets: 'Alle Märkte',
    connectWallet: 'Wallet verbinden',
    noDataYet: 'Noch keine Daten',
    loading: 'Wird geladen...',
    settings: 'Einstellungen',
    language: 'Sprache',
  },
  vi: {
    trade: 'Giao dịch',
    portfolio: 'Danh mục',
    vaults: 'Kho tiền',
    history: 'Lịch sử',
    rewards: 'Phần thưởng',
    leaderboard: 'Bảng xếp hạng',
    apiSdk: 'API & SDK Khách',
    docs: 'Sách trắng',
    ecosystem: 'Hệ sinh thái',
    developerSuite: 'Bộ công cụ Nhà phát triển',
    systemWhitepaper: 'Sách trắng Kiến trúc',
    onChainExplorer: 'Trình khám phá On-Chain',
    securityInfra: 'Bảo mật & Hạ tầng',
    sessionKeys: 'Khóa phiên 1-Chạm',
    contractSource: 'Mã nguồn Hợp đồng',
    growthRankings: 'Tăng trưởng & Thứ hạng',
    markPrice: 'Giá Mark',
    oraclePrice: 'Giá Oracle',
    change24h: 'Thay đổi 24h',
    volume24h: 'Khối lượng 24h',
    openInterest: 'Hợp đồng mở',
    fundingRate: 'Phí Funding / 1h',
    placeOrder: 'Đặt lệnh',
    buyLong: 'Mua / Long',
    sellShort: 'Bán / Short',
    market: 'Thị trường',
    limit: 'Giới hạn',
    stopMarket: 'Stop Thị trường',
    stopLimit: 'Stop Giới hạn',
    margin: 'Ký quỹ',
    leverage: 'Đòn bẩy',
    priceImpact: 'Tác động giá',
    maxSlippage: 'Trượt giá tối đa',
    deposit: 'Nạp tiền',
    withdraw: 'Rút tiền',
    availableToTrade: 'Ký quỹ khả dụng',
    currentPosition: 'Vị thế hiện tại',
    stopTriggerPrice: 'Giá Kích hoạt Stop',
    limitPrice: 'Giá Giới hạn',
    positions: 'Vị thế mở',
    openOrders: 'Lệnh chờ duyệt',
    tradeHistory: 'Lịch sử giao dịch',
    entryPrice: 'Giá vào lệnh',
    liqPrice: 'Giá Thanh lý',
    pnl: 'Lợi nhuận (PnL)',
    action: 'Thao tác',
    closePosition: 'Đóng vị thế',
    editTpSl: 'Sửa TP/SL',
    sharePnl: 'Chia sẻ PnL',
    cancelOrder: 'Hủy lệnh',
    orderBook: 'Sổ lệnh',
    trades: 'Giao dịch gần đây',
    priceUsdc: 'Giá (USDC)',
    size: 'Khối lượng',
    total: 'Tổng số',
    spread: 'Chênh lệch',
    liquidityVault: 'Kho Thanh Khoản',
    totalValueLocked: 'Tổng Giá Trị Khóa (TVL)',
    estimatedApr: 'APR Ước Tính',
    totalSharesMinted: 'Tổng Cổ Phần Đã Phát Hành',
    yourPoolShare: 'Phần Pool Của Bạn',
    yourStakedBalance: 'Số Dư Staking Của Bạn',
    depositUsdc: 'Nạp USDC',
    withdrawUsdc: 'Rút USDC',
    stakingYield: 'Lợi Suất Staking',
    elpPrice: 'Giá ELP',
    dailyYield: 'Lợi Suất Hàng Ngày',
    redeemShares: 'Đổi Cổ Phần',
    referralProgram: 'Chương Trình Giới Thiệu',
    unclaimedKickback: 'Hoa Hồng Chưa Nhận',
    lifetimeEarnings: 'Thu Nhập Tích Lũy',
    referredTraders: 'Trader Được Giới Thiệu',
    tradingVolume30d: 'Khối Lượng 30 Ngày',
    vipTier: 'Hạng VIP',
    feeDiscount: 'Giảm Phí',
    copyReferralLink: 'Sao Chép Liên Kết Giới Thiệu',
    claimRewards: 'Nhận Phần Thưởng',
    rank: 'Hạng',
    trader: 'Nhà Giao Dịch',
    realizedPnl: 'Lãi/Lỗ Thực Hiện',
    winRate: 'Tỷ Lệ Thắng',
    totalTrades: 'Tổng Giao Dịch',
    yourRank: 'Hạng Của Bạn',
    tradeLog: 'Nhật Ký Giao Dịch',
    exitPrice: 'Giá Thoát',
    feePaid: 'Phí Đã Trả',
    txHash: 'Mã Tx',
    filterByMarket: 'Lọc Theo Thị Trường',
    allMarkets: 'Tất Cả Thị Trường',
    connectWallet: 'Kết Nối Ví',
    noDataYet: 'Chưa có dữ liệu',
    loading: 'Đang tải...',
    settings: 'Cài Đặt',
    language: 'Ngôn Ngữ',
  },
  tr: {
    trade: 'Ticaret',
    portfolio: 'Portföy',
    vaults: 'Kasa',
    history: 'Geçmiş',
    rewards: 'Ödüller',
    leaderboard: 'Liderlik Tablosu',
    apiSdk: 'API ve İstemci SDK',
    docs: 'Sistem Teknik Dokümanı',
    ecosystem: 'Ekosistem',
    developerSuite: 'Geliştirici Araçları',
    systemWhitepaper: 'Sistem Dokümanı',
    onChainExplorer: 'Zincir Üstü Gezgin',
    securityInfra: 'Güvenlik ve Altyapı',
    sessionKeys: 'Tek Tık Oturum Anahtarları',
    contractSource: 'Sözleşme Kaynak Kodu',
    growthRankings: 'Büyüme ve Sıralama',
    markPrice: 'Gösterge Fiyatı',
    oraclePrice: 'Kahin Fiyatı',
    change24h: '24s Değişim',
    volume24h: '24s Hacim',
    openInterest: 'Açık Pozisyonlar',
    fundingRate: 'Fonlama / 1s',
    placeOrder: 'Emir Ver',
    buyLong: 'Al / Long',
    sellShort: 'Sat / Short',
    market: 'Piyasa',
    limit: 'Limit',
    stopMarket: 'Stop Piyasa',
    stopLimit: 'Stop Limit',
    margin: 'Teminat',
    leverage: 'Kaldıraç',
    priceImpact: 'Fiyat Etkisi',
    maxSlippage: 'Maksimum Kayma',
    deposit: 'Yatır',
    withdraw: 'Çek',
    availableToTrade: 'Kullanılabilir Bakiye',
    currentPosition: 'Mevcut Pozisyon',
    stopTriggerPrice: 'Tetikleme Fiyatı',
    limitPrice: 'Limit Fiyat',
    positions: 'Pozisyonlar',
    openOrders: 'Açık Emirler',
    tradeHistory: 'İşlem Geçmişi',
    entryPrice: 'Giriş Fiyatı',
    liqPrice: 'Tasfiye Fiyatı',
    pnl: 'Kar/Zarar (PnL)',
    action: 'İşlem',
    closePosition: 'Pozisyonu Kapat',
    editTpSl: 'TP/SL Düzenle',
    sharePnl: 'PnL Paylaş',
    cancelOrder: 'Emri İptal Et',
    orderBook: 'Emir Defteri',
    trades: 'Son İşlemler',
    priceUsdc: 'Fiyat (USDC)',
    size: 'Miktar',
    total: 'Toplam',
    spread: 'Fark',
    liquidityVault: 'Likidite Kasası',
    totalValueLocked: 'Toplam Kilitli Değer (TVL)',
    estimatedApr: 'Tahmini APR',
    totalSharesMinted: 'Toplam Basılan Pay',
    yourPoolShare: 'Havuz Payınız',
    yourStakedBalance: 'Stake Bakiyeniz',
    depositUsdc: 'USDC Yatır',
    withdrawUsdc: 'USDC Çek',
    stakingYield: 'Staking Getirisi',
    elpPrice: 'ELP Fiyatı',
    dailyYield: 'Günlük Getiri',
    redeemShares: 'Payları Geri Al',
    referralProgram: 'Yönlendirme Programı',
    unclaimedKickback: 'Talep Edilmemiş Komisyon',
    lifetimeEarnings: 'Toplam Kazanç',
    referredTraders: 'Yönlendirilen Traderlar',
    tradingVolume30d: '30 Günlük İşlem Hacmi',
    vipTier: 'VIP Seviyesi',
    feeDiscount: 'Ücret İndirimi',
    copyReferralLink: 'Yönlendirme Linkini Kopyala',
    claimRewards: 'Ödülleri Talep Et',
    rank: 'Sıra',
    trader: 'Trader',
    realizedPnl: 'Gerçekleşen Kar/Zarar',
    winRate: 'Kazanma Oranı',
    totalTrades: 'Toplam İşlem',
    yourRank: 'Sıralamanız',
    tradeLog: 'İşlem Günlüğü',
    exitPrice: 'Çıkış Fiyatı',
    feePaid: 'Ödenen Ücret',
    txHash: 'Tx Hash',
    filterByMarket: 'Pazara Göre Filtrele',
    allMarkets: 'Tüm Pazarlar',
    connectWallet: 'Cüzdan Bağla',
    noDataYet: 'Henüz veri yok',
    loading: 'Yükleniyor...',
    settings: 'Ayarlar',
    language: 'Dil',
  },
};

interface LanguageContextType {
  language: SupportedLanguage;
  setLanguage: (lang: SupportedLanguage) => void;
  numberFormat: string;
  setNumberFormat: (fmt: string) => void;
  t: (key: keyof Translations) => string;
  formatNum: (val: number, decimals?: number) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<SupportedLanguage>('en');
  const [numberFormat, setNumberFormat] = useState<string>('1,234.56');

  const t = useCallback(
    (key: keyof Translations) => {
      const dict = TRANSLATIONS[language] || TRANSLATIONS['en'];
      return dict[key] || TRANSLATIONS['en'][key] || key;
    },
    [language]
  );

  const formatNum = useCallback(
    (val: number, decimals: number = 2) => {
      if (isNaN(val)) return '0.00';
      const fixed = val.toFixed(decimals);
      const [intPart, decPart] = fixed.split('.');

      let formattedInt = intPart;
      if (numberFormat === '1,234.56') {
        formattedInt = intPart.replace(/\B(?=(\d{3})+(?!\d))/g, ',');
        return decPart !== undefined ? `${formattedInt}.${decPart}` : formattedInt;
      } else if (numberFormat === '1.234,56') {
        formattedInt = intPart.replace(/\B(?=(\d{3})+(?!\d))/g, '.');
        return decPart !== undefined ? `${formattedInt},${decPart}` : formattedInt;
      } else if (numberFormat === '1234,56') {
        return decPart !== undefined ? `${intPart},${decPart}` : intPart;
      } else if (numberFormat === '1 234,56') {
        formattedInt = intPart.replace(/\B(?=(\d{3})+(?!\d))/g, ' ');
        return decPart !== undefined ? `${formattedInt},${decPart}` : formattedInt;
      }

      return fixed;
    },
    [numberFormat]
  );

  return (
    <LanguageContext.Provider value={{ language, setLanguage, numberFormat, setNumberFormat, t, formatNum }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
